### ISSUE TITLE
Broken links on freesewing.org home page

### ISSUE THREAD

**Issue by Slylele** [freesewing/freesewing.dev#130]
Here are the broken url available at home page of the website (jsut below each url, you can find the correct one for correction):

https://en.freesewing.org/docs/faq
https://en.freesewing.org/docs/about/faq

https://freesewing.dev/translator
https://freesewing.dev/guides/translator

https://freesewing.dev/contributor
https://freesewing.dev/guides/contributor

https://freesewing.dev/editor
https://freesewing.dev/guides/editor

**Comment by joostdecock** [comment]
Nice work :) I'll fix these ASAP

**Comment by joostdecock** [comment]
Sorry for the delay, it's been fixed.
