### ISSUE TITLE
Broken link on freesewing.dev

### ISSUE THREAD

**Issue by jwill** [freesewing/freesewing.dev#230]
Please include the URL of the page that has the broken link on it

https://freesewing.dev/plugins/svgattr

**Comment by joostdecock** [comment]
Thank you for taking the time to report this @jwill  We re-structured the docs recently, seems you stumbled on an old link.

The correct URL is: https://freesewing.dev/reference/plugins/svgattr/

I'll see if I can hunt down the broken link.

**Comment by jwill** [comment]
It was on the tutorial pattern...one sec for link.

https://freesewing.dev/tutorials/pattern-design/completing-your-pattern/

in the section titled **Seam allowance**

**Comment by amysews** [comment]
There doesn't appear to be a link anymore to plugins in this section https://freesewing.dev/tutorials/pattern-design/completing-your-pattern/#seam-allowance

I have noticed another broken link in that section though - 'Adding Text' is trying to take you to https://freesewing.dev/concepts/adding-text which no longer exists. I might have a go at fixing this and see if there are any more on this page if I get some time - should this be raised on a new issue or generalise this one to capture the broaded issue of broken links?

**Comment by amysews** [comment]
Found 3 broken urls under /concepts/

https://freesewing.dev/concepts/adding-text 
https://freesewing.dev/concepts/beziercurves
https://freesewing.dev/concepts/new-design

I'm happy to change them but I'm not sure what to so would need guidance on that.

**Comment by joostdecock** [comment]
That content is kept in our Markdown repository. Specifically the file in question is this one: https://github.com/freesewing/markdown/blob/develop/dev/tutorials/pattern-design/completing-your-pattern/en.md

You can update the links and submit a pull request, then we'll re-deploy the site with them :+1: 

Thank you for doing this :slightly_smiling_face:

**Comment by joostdecock** [comment]
I'm sure there's more broken links, but the site has been redesigned (and this is very old) so I'm closing this.
