### ISSUE TITLE
Broken link on freesewing.dev

### ISSUE THREAD

**Issue by ricekream** [freesewing/freesewing.dev#268]
https://freesewing.org/docs/about/model-graph

When clicking "What is this?" Under person graph.

**Comment by joostdecock** [comment]
Thank you for reporting this. It's fixed in https://github.com/freesewing/freesewing.org/commit/c67b1637aa89031dff97f3ee1f06a66944bff650 
It will take a while before it appears on the site, but it's in the pipeline, so I'm closing this.
