### ISSUE TITLE
Broken link on freesewing.dev

### ISSUE THREAD

**Issue by polymatter** [freesewing/freesewing.dev#315]
On https://www.npmjs.com/package/create-freesewing-pattern in the "About FreeSewing" section the words "getting started" point to "https://freesewing.dev/start" which is invalid.

Replication Steps:
1. Go to "https://www.npmjs.com/package/create-freesewing-pattern#about-freesewing-"
2. Click on the words "getting started"

Expected Result: Land on a "Getting Started" page
Actual Restult: Can not find page result

**Comment by joostdecock** [comment]
Thank you for reporting this @polymatter . I've updated [the original README file](https://github.com/freesewing/freesewing/blob/develop/packages/create-freesewing-pattern/README.md). The content on the NPM registry will be updated next time we publish a new version.
