### ISSUE TITLE
Fix missing scrollbar on menu

### ISSUE THREAD

**Issue by jliu1016** [freesewing/freesewing.dev#4]
"PS. I've been using freesewing.dev/api a lot, and something is seriously bothering me. The right side where the 'menu' is is missing the scrollbars when the main part of the window is large. So you have to scroll the main part all the way down to get to the last part of the 'menu'. Here's a screenshot:
 
The green arrow points at the scrollbar of the whole window. The red arrow points to where a scrollbar should be, but isn't. This can be seen on both Chrome and Edge on Windows, and on Firefox and Chromium on Ubuntu."

**Comment by joostdecock** [comment]
Implemented and deployed. Ping @woutervdub
