### ISSUE TITLE
Update links to gitter.im

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing.dev#7]
Since we've renamed our rooms, we need to update the links to them

**Comment by don-smith** [comment]
@joostdecock I can't seem to find the actual content from freesewing.dev inside this repo. Is the content being hosted elsewhere?

**Comment by joostdecock** [comment]
The content for both the .org and .dev websites is kept in our `markdown` repository: https://github.com/freesewing/markdown/tree/develop/dev
